# color theme
include colors/mocha.conf

# font
font_family JetBrains Mono Nerd
disable_ligatures always
font_size 12

enable_audio_bell no

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

confirm_os_window_close 0

