# color theme
include colors/mocha.conf

# font
font_family JetBrains Mono Nerd
disable_ligatures always
font_size 11

# orientation: top right down left
window_padding_width 5 5 8 5 

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

confirm_os_window_close 0

cursor_blink_interval 0
